const fs = require('fs');
const path = require('path');

let postArticle = fs.readFileSync('scripts/post-article.js', 'utf8');

const oldPromptRegex = /\/\/ --- Generate Social Media Posts \(V3 Ultra-Dense NotebookLM-Style\) ---[\s\S]*?console\.log\("Social media data saved successfully\."\);\n  \}/;

const newPrompt = `// --- Generate Social Media Posts (V4 True Illustration-First) ---
  const socialPrompt = \`You are the Chief Financial Educator and Art Director for TrustPointFin.

OBJECTIVE:
Create a "Financial Mini-Lesson" for Instagram heavily reliant on ACTUAL VISUAL ILLUSTRATIONS and STORYTELLING.
Do NOT just generate text. The primary teaching tool must be the illustration (60-70% of the slide).
Use NotebookLM-style visual education: illustrated people, characters, visual metaphors, coins, plants, buildings, process flows.

TEACHING FORMAT (Pick ONE):
- STORY (Characters Aman/Neha/Raj in a situation)
- METAPHOR (e.g. Tree growing = compounding)
- COMPARISON (Two contrasting scenes)
- PROCESS DIAGRAM
- SCENARIO

SLIDE STRUCTURE (6-9 slides):
Every slide must have a 'visual_spec' object detailing the illustration to be generated by the Illustration Engine.

LANGUAGE:
Hinglish (Devanagari script + English financial terms).

OUTPUT FORMAT (RAW JSON ONLY):
{
  "topic": "\${topic}",
  "teaching_objective": "...",
  "format": "STORY|METAPHOR|COMPARISON|DIAGRAM",
  "visual_style": "Hand-drawn educational|Modern editorial|Character storytelling",
  "slides": [
    {
      "slide_number": 1,
      "purpose": "context",
      "headline": "Main text",
      "core_explanation": "Supporting text (keep it concise, let the visual do the work)",
      "visual_spec": {
          "visual_concept": "Describe the core visual idea (e.g., A young man holding a tiny plant, looking confused at a giant oak tree).",
          "visual_type": "illustration|character|metaphor|diagram",
          "characters": ["Aman (young beginner)"],
          "objects": ["Small plant", "Oak tree"],
          "scene": "A sunny garden",
          "composition": "Aman on the left, oak tree on the right",
          "image_generation_prompt": "A hand-drawn educational illustration of a young man looking confused at a tiny plant in his hands, with a giant oak tree in the background. Financial theme, modern style, clean white background."
      },
      "annotation": "A small tip or key takeaway.",
      "cta": null
    }
  ],
  "caption": "Instagram caption..."
}

IMPORTANT: The 'image_generation_prompt' must be a highly detailed prompt ready to be sent to an AI Image Generator (like DALL-E/Midjourney) to create the exact illustration needed for the slide.\`;

  let socialJson = null;
  let attempts = 0;
  const MAX_ATTEMPTS = 3;

  while (attempts < MAX_ATTEMPTS && !socialJson) {
      attempts++;
      console.log(\`Generating V4 true-illustration content (Attempt \${attempts}/\${MAX_ATTEMPTS})...\`);
      try {
          const socialResponse = await generateContentWithRetry(socialPrompt);
          let rawText = socialResponse.response.text();
          rawText = rawText.replace(/\\\`\\\`\\\`json/g, '').replace(/\\\`\\\`\\\`/g, '').trim();
          
          const parsed = JSON.parse(rawText);
          
          const { validateSocialContent } = require("./content-quality-gate.js");
          const qgResult = validateSocialContent(parsed);
          
          if (qgResult.valid) {
              socialJson = parsed;
              console.log("Quality Gate PASSED!");
          } else {
              console.log("Quality Gate FAILED:", qgResult.reason);
          }
      } catch (e) {
          console.log("JSON parsing or generation error:", e.message);
      }
  }

  if (!socialJson) {
      console.error("Failed to generate valid social content after 3 attempts.");
  } else {
      fs.writeFileSync(path.join(ROOT, "latest_slides.json"), JSON.stringify(socialJson, null, 2), "utf-8");
      const socialMarkdown = \`# Social Media Posts (V4)\\n*Generated on \${dateStr} for topic: "\${topic}"*\\n\\n---\\n## 📱 Caption\\n\${socialJson.caption}\\n\`;
      fs.writeFileSync(SOCIAL_PATH, socialMarkdown, "utf-8");
      console.log("Social media data saved successfully.");
  }`;

postArticle = postArticle.replace(oldPromptRegex, newPrompt);
fs.writeFileSync('scripts/post-article.js', postArticle, 'utf8');
console.log('Successfully upgraded post-article.js to V4 True-Illustration prompt.');
